"""add mpesa fields

Revision ID: 7eae74baae2b
Revises: d83404d4ada1
Create Date: 2026-02-10 02:22:23.668366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eae74baae2b'
down_revision = 'd83404d4ada1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('mpesa_receipt')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
