"""add approval and rejection reason columns to projects

Revision ID: d83404d4ada1
Revises: e2af49a9974c
Create Date: 2026-02-09 02:17:03.458698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83404d4ada1'
down_revision = 'e2af49a9974c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approval_reason')

    # ### end Alembic commands ###
