export const PRODUCTS = [
  {
    id: 1,
    name: 'Moringa Developer Hoodie',
    price: 2500,
    image: '👕',
    color: 'Deep Blue',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: 'Innovation Coffee Mug',
    price: 800,
    image: '☕',
    color: 'White',
    sizes: ['One Size'],
    inStock: true,
    rating: 4.5,
    reviews: 45,
  },
  {
    id: 3,
    name: 'Tech Sticker Pack',
    price: 300,
    image: '🎨',
    color: 'Multi-color',
    sizes: ['One Size'],
    inStock: true,
    rating: 4.6,
    reviews: 67,
  },
  {
    id: 4,
    name: 'Moringa Branded Cap',
    price: 1200,
    image: '🧢',
    color: 'Black',
    sizes: ['One Size'],
    inStock: true,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 5,
    name: 'Developer T-Shirt',
    price: 1500,
    image: '👔',
    color: 'Navy Blue',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    rating: 4.9,
    reviews: 156,
  },
  {
    id: 6,
    name: 'Moringa Water Bottle',
    price: 1000,
    image: '🚰',
    color: 'Silver',
    sizes: ['One Size'],
    inStock: true,
    rating: 4.4,
    reviews: 38,
  },
]
