export const PROJECTS = [
  {
    id: 1,
    title: 'HealthTech Appointment System',
    description: 'AI-powered healthcare appointment booking platform with real-time clinic sync.',
    longDescription: `Our HealthTech Appointment System revolutionizes how clinics manage patient appointments.\nBuilt with modern web technologies, it provides a seamless experience for both healthcare providers and patients.\n\nKey Features:\n• Real-time appointment scheduling across multiple clinics\n• AI-powered availability optimization\n• Automated SMS/Email reminders\n• Patient history and preferences tracking\n• Analytics dashboard for clinic administrators\n• Mobile-responsive design\n\nThe platform has been tested with 5 major clinics in Nairobi and shows 40% reduction in no-shows.`,
    category: 'HealthTech',
    author: 'Team Alpha',
    technologies: ['React', 'Node.js', 'PostgreSQL'],
    views: 1250,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1519494080410-f9aa8f52f274?auto=format&fit=crop&w=400&q=80',
    reviews: 23,
    liveLink: 'https://example.com',
    githubLink: 'https://github.com/example',
    createdAt: '2024-01-15',
    status: 'Active',
    teamSize: 3,
    teamMembers: ['Alice Johnson', 'Bob Smith', 'Carol Davis'],
  },
  {
    id: 2,
    title: 'EdTech Learning Analytics Dashboard',
    description: 'Real-time student performance analytics with predictive learning paths.',
    longDescription: 'Real-time student performance analytics with predictive learning paths and insights for teachers.',
    category: 'EdTech',
    author: 'Team Beta',
    technologies: ['Next.js', 'Python', 'TensorFlow'],
    views: 980,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
    reviews: 12,
    liveLink: 'https://example.com',
    githubLink: 'https://github.com/example',
    createdAt: '2024-02-01',
    status: 'Active',
    teamSize: 4,
    teamMembers: ['Daniel Kim', 'Eva Green'],
  },
  {
    id: 3,
    title: 'FinTech Mobile Wallet',
    description: 'Secure mobile payment solution with peer-to-peer transfers.',
    longDescription: 'Secure mobile payment solution with wallet features and seamless P2P transfers.',
    category: 'FinTech',
    author: 'Team Gamma',
    technologies: ['Flutter', 'Firebase', 'Stripe'],
    views: 1540,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
    reviews: 45,
    liveLink: 'https://example.com',
    githubLink: 'https://github.com/example',
    createdAt: '2024-03-10',
    status: 'Active',
    teamSize: 5,
    teamMembers: ['Fiona Lee', 'George Brown'],
  },
  {
    id: 4,
    title: 'AgriTech Smart Farming',
    description: 'IoT and AI-based crop monitoring for optimal yield.',
    longDescription: 'IoT and AI-based crop monitoring platform helping farmers maximize yields.',
    category: 'AgriTech',
    author: 'Team Delta',
    technologies: ['Python', 'Arduino', 'AWS'],
    views: 850,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
    reviews: 8,
    liveLink: 'https://example.com',
    githubLink: 'https://github.com/example',
    createdAt: '2024-04-01',
    status: 'Active',
    teamSize: 3,
    teamMembers: ['Ian M', 'Judy Z'],
  },
  {
    id: 5,
    title: 'Social Media Analytics Tool',
    description: 'Real-time social media performance tracking and insights generation.',
    longDescription: 'Real-time social media performance tracking and insights generation.',
    category: 'SaaS',
    author: 'Team Echo',
    technologies: ['React', 'MongoDB', 'Express'],
    views: 650,
    rating: 4.5,
    reviews: 5,
    createdAt: '2024-05-12',
    status: 'Prototype',
    teamSize: 2,
    teamMembers: ['Kyle', 'Lana'],
  },
  {
    id: 6,
    title: 'E-Commerce Platform',
    description: 'Full-stack marketplace with payment integration and seller dashboard.',
    longDescription: 'Full-stack marketplace with payment integration and seller dashboard.',
    category: 'E-Commerce',
    author: 'Team Foxtrot',
    technologies: ['Next.js', 'Prisma', 'Stripe'],
    views: 1100,
    rating: 4.8,
    reviews: 30,
    createdAt: '2024-06-22',
    status: 'Active',
    teamSize: 6,
    teamMembers: ['Mona', 'Nate'],
  },
  {
    id: 7,
    title: 'AI Resume Parser',
    description: 'Machine learning-powered resume analysis for recruitment teams.',
    longDescription: 'Machine learning-powered resume analysis for recruitment teams.',
    category: 'AI/ML',
    author: 'Team Golf',
    technologies: ['Python', 'TensorFlow', 'FastAPI'],
    views: 750,
    rating: 4.7,
    reviews: 9,
    createdAt: '2024-07-05',
    status: 'Prototype',
    teamSize: 3,
    teamMembers: ['Olivia', 'Paul'],
  },
  {
    id: 8,
    title: 'Real Estate Search Engine',
    description: 'Advanced search with property recommendations and virtual tours.',
    longDescription: 'Advanced search with property recommendations and virtual tours.',
    category: 'Real Estate',
    author: 'Team Hotel',
    technologies: ['React', 'Node.js', 'Elasticsearch'],
    views: 920,
    rating: 4.6,
    reviews: 14,
    createdAt: '2024-08-15',
    status: 'Active',
    teamSize: 4,
    teamMembers: ['Quinn', 'Rita'],
  },
]
